export function fromwire_tu16(buffer: any): (number | Buffer)[];
export function fromwire_tu32(buffer: any): (number | Buffer)[];
export function fromwire_tu64(buffer: any): (number | Buffer)[];
export function fromwire_u16(buffer: any): any[];
export function fromwire_u32(buffer: any): any[];
export function fromwire_u64(buffer: any): any[];
export function fromwire_byte(buffer: any): any[];
export function fromwire_chain_hash(buffer: any): any[];
export function fromwire_channel_id(buffer: any): any[];
export function fromwire_sha256(buffer: any): any[];
export function fromwire_point(buffer: any): any[];
export function fromwire_point32(buffer: any): any[];
export function fromwire_bip340sig(buffer: any): any[];
export function fromwire_array_utf8(buffer: any, len: any): any[];
export function fromwire_bigsize(buffer: any): any[];
import { Buffer } from 'buffer';
