export function towire_offer_chains(value: any): Buffer;
export function fromwire_offer_chains(buffer: any): any[];
export function towire_offer_currency(value: any): Buffer;
export function fromwire_offer_currency(buffer: any): any;
export function towire_offer_amount(value: any): Buffer;
export function fromwire_offer_amount(buffer: any): any;
export function towire_offer_description(value: any): Buffer;
export function fromwire_offer_description(buffer: any): any;
export function towire_offer_features(value: any): Buffer;
export function fromwire_offer_features(buffer: any): any;
export function towire_offer_absolute_expiry(value: any): Buffer;
export function fromwire_offer_absolute_expiry(buffer: any): any;
export function towire_offer_paths(value: any): Buffer;
export function fromwire_offer_paths(buffer: any): any;
export function towire_offer_issuer(value: any): Buffer;
export function fromwire_offer_issuer(buffer: any): any;
export function towire_offer_quantity_max(value: any): Buffer;
export function fromwire_offer_quantity_max(buffer: any): any;
export function towire_offer_recurrence(value: any): Buffer;
export function fromwire_offer_recurrence(buffer: any): {
    time_unit: any;
    period: any;
};
export function towire_offer_recurrence_paywindow(value: any): Buffer;
export function fromwire_offer_recurrence_paywindow(buffer: any): {
    seconds_before: any;
    proportional_amount: any;
    seconds_after: any;
};
export function towire_offer_recurrence_limit(value: any): Buffer;
export function fromwire_offer_recurrence_limit(buffer: any): any;
export function towire_offer_recurrence_base(value: any): Buffer;
export function fromwire_offer_recurrence_base(buffer: any): {
    start_any_period: any;
    basetime: any;
};
export function towire_offer_node_id(value: any): Buffer;
export function fromwire_offer_node_id(buffer: any): any;
export function towire_offer_signature(value: any): Buffer;
export function fromwire_offer_signature(buffer: any): any;
export function towire_invoice_request_chains(value: any): Buffer;
export function fromwire_invoice_request_chains(buffer: any): any;
export function towire_invoice_request_offer_id(value: any): Buffer;
export function fromwire_invoice_request_offer_id(buffer: any): any;
export function towire_invoice_request_amount(value: any): Buffer;
export function fromwire_invoice_request_amount(buffer: any): any;
export function towire_invoice_request_features(value: any): Buffer;
export function fromwire_invoice_request_features(buffer: any): any;
export function towire_invoice_request_quantity(value: any): Buffer;
export function fromwire_invoice_request_quantity(buffer: any): any;
export function towire_invoice_request_recurrence_counter(value: any): Buffer;
export function fromwire_invoice_request_recurrence_counter(buffer: any): any;
export function towire_invoice_request_recurrence_start(value: any): Buffer;
export function fromwire_invoice_request_recurrence_start(buffer: any): any;
export function towire_invoice_request_payer_key(value: any): Buffer;
export function fromwire_invoice_request_payer_key(buffer: any): any;
export function towire_invoice_request_payer_note(value: any): Buffer;
export function fromwire_invoice_request_payer_note(buffer: any): any;
export function towire_invoice_request_payer_info(value: any): Buffer;
export function fromwire_invoice_request_payer_info(buffer: any): any;
export function towire_invoice_request_replace_invoice(value: any): Buffer;
export function fromwire_invoice_request_replace_invoice(buffer: any): any;
export function towire_invoice_request_payer_signature(value: any): Buffer;
export function fromwire_invoice_request_payer_signature(buffer: any): any;
export function towire_invoice_chains(value: any): Buffer;
export function fromwire_invoice_chains(buffer: any): any;
export function towire_invoice_offer_id(value: any): Buffer;
export function fromwire_invoice_offer_id(buffer: any): any;
export function towire_invoice_amount(value: any): Buffer;
export function fromwire_invoice_amount(buffer: any): any;
export function towire_invoice_description(value: any): Buffer;
export function fromwire_invoice_description(buffer: any): any;
export function towire_invoice_features(value: any): Buffer;
export function fromwire_invoice_features(buffer: any): any;
export function towire_invoice_paths(value: any): Buffer;
export function fromwire_invoice_paths(buffer: any): any;
export function towire_invoice_blindedpay(value: any): Buffer;
export function fromwire_invoice_blindedpay(buffer: any): any;
export function towire_invoice_blinded_capacities(value: any): Buffer;
export function fromwire_invoice_blinded_capacities(buffer: any): any;
export function towire_invoice_issuer(value: any): Buffer;
export function fromwire_invoice_issuer(buffer: any): any;
export function towire_invoice_node_id(value: any): Buffer;
export function fromwire_invoice_node_id(buffer: any): any;
export function towire_invoice_quantity(value: any): Buffer;
export function fromwire_invoice_quantity(buffer: any): any;
export function towire_invoice_refund_for(value: any): Buffer;
export function fromwire_invoice_refund_for(buffer: any): any;
export function towire_invoice_recurrence_counter(value: any): Buffer;
export function fromwire_invoice_recurrence_counter(buffer: any): any;
export function towire_invoice_recurrence_start(value: any): Buffer;
export function fromwire_invoice_recurrence_start(buffer: any): any;
export function towire_invoice_recurrence_basetime(value: any): Buffer;
export function fromwire_invoice_recurrence_basetime(buffer: any): any;
export function towire_invoice_payer_key(value: any): Buffer;
export function fromwire_invoice_payer_key(buffer: any): any;
export function towire_invoice_payer_note(value: any): Buffer;
export function fromwire_invoice_payer_note(buffer: any): any;
export function towire_invoice_payer_info(value: any): Buffer;
export function fromwire_invoice_payer_info(buffer: any): any;
export function towire_invoice_created_at(value: any): Buffer;
export function fromwire_invoice_created_at(buffer: any): any;
export function towire_invoice_payment_hash(value: any): Buffer;
export function fromwire_invoice_payment_hash(buffer: any): any;
export function towire_invoice_relative_expiry(value: any): Buffer;
export function fromwire_invoice_relative_expiry(buffer: any): any;
export function towire_invoice_cltv(value: any): Buffer;
export function fromwire_invoice_cltv(buffer: any): any;
export function towire_invoice_fallbacks(value: any): Buffer;
export function fromwire_invoice_fallbacks(buffer: any): {
    fallbacks: any;
};
export function towire_invoice_refund_signature(value: any): Buffer;
export function fromwire_invoice_refund_signature(buffer: any): any;
export function towire_invoice_signature(value: any): Buffer;
export function fromwire_invoice_signature(buffer: any): any;
export function towire_onionmsg_path(value: any): Buffer;
export function fromwire_onionmsg_path(buffer: any): any[];
export function towire_blinded_path(value: any): Buffer;
export function fromwire_blinded_path(buffer: any): any[];
export function towire_blinded_payinfo(value: any): Buffer;
export function fromwire_blinded_payinfo(buffer: any): any[];
export function towire_fallback_address(value: any): Buffer;
export function fromwire_fallback_address(buffer: any): any[];
export const tlv_offer: {
    2: (string | typeof towire_offer_chains | typeof fromwire_offer_chains)[];
    4: (string | typeof fromwire_offer_description)[];
    6: (string | typeof fromwire_offer_currency)[];
    8: (string | typeof fromwire_offer_amount)[];
    10: (string | typeof fromwire_offer_description)[];
    12: (string | typeof fromwire_offer_features)[];
    14: (string | typeof fromwire_offer_absolute_expiry)[];
    16: (string | typeof fromwire_offer_paths)[];
    18: (string | typeof fromwire_offer_issuer)[];
    20: (string | typeof fromwire_offer_quantity_max)[];
    22: (string | typeof fromwire_offer_node_id)[];
    26: (string | typeof towire_offer_recurrence | typeof fromwire_offer_recurrence)[];
    64: (string | typeof towire_offer_recurrence_paywindow | typeof fromwire_offer_recurrence_paywindow)[];
    66: (string | typeof fromwire_offer_recurrence_limit)[];
    28: (string | typeof towire_offer_recurrence_base | typeof fromwire_offer_recurrence_base)[];
    240: (string | typeof fromwire_offer_signature)[];
};
export const tlv_invoice_request: {
    2: (string | typeof fromwire_invoice_request_chains)[];
    4: (string | typeof fromwire_invoice_request_offer_id)[];
    8: (string | typeof fromwire_invoice_request_amount)[];
    12: (string | typeof fromwire_invoice_request_features)[];
    32: (string | typeof fromwire_invoice_request_quantity)[];
    36: (string | typeof fromwire_invoice_request_recurrence_counter)[];
    68: (string | typeof fromwire_invoice_request_recurrence_start)[];
    38: (string | typeof fromwire_invoice_request_payer_key)[];
    39: (string | typeof fromwire_invoice_request_payer_note)[];
    50: (string | typeof fromwire_invoice_request_payer_info)[];
    56: (string | typeof fromwire_invoice_request_replace_invoice)[];
    240: (string | typeof fromwire_invoice_request_payer_signature)[];
};
export const tlv_invoice: {
    2: (string | typeof fromwire_invoice_chains)[];
    4: (string | typeof fromwire_invoice_offer_id)[];
    8: (string | typeof fromwire_invoice_amount)[];
    10: (string | typeof fromwire_invoice_description)[];
    12: (string | typeof fromwire_invoice_features)[];
    16: (string | typeof fromwire_invoice_paths)[];
    18: (string | typeof fromwire_invoice_blindedpay)[];
    19: (string | typeof fromwire_invoice_blinded_capacities)[];
    20: (string | typeof fromwire_invoice_issuer)[];
    30: (string | typeof fromwire_invoice_node_id)[];
    32: (string | typeof fromwire_invoice_quantity)[];
    34: (string | typeof fromwire_invoice_refund_for)[];
    36: (string | typeof fromwire_invoice_recurrence_counter)[];
    68: (string | typeof fromwire_invoice_recurrence_start)[];
    64: (string | typeof fromwire_invoice_recurrence_basetime)[];
    38: (string | typeof fromwire_invoice_payer_key)[];
    39: (string | typeof fromwire_invoice_payer_note)[];
    50: (string | typeof fromwire_invoice_payer_info)[];
    40: (string | typeof fromwire_invoice_created_at)[];
    42: (string | typeof fromwire_invoice_payment_hash)[];
    44: (string | typeof fromwire_invoice_relative_expiry)[];
    46: (string | typeof fromwire_invoice_cltv)[];
    48: (string | typeof towire_invoice_fallbacks | typeof fromwire_invoice_fallbacks)[];
    52: (string | typeof fromwire_invoice_refund_signature)[];
    240: (string | typeof fromwire_invoice_signature)[];
};
import { Buffer } from 'buffer';
