export const tagParser: {
    0: (string | ((buf: any) => any))[];
    2: (string | typeof fromwire_offer_chains)[];
    4: (string | ((buf: any) => any))[];
    6: (string | typeof fromwire_offer_currency)[];
    8: (string | typeof fromwire_offer_amount)[];
    10: (string | typeof fromwire_offer_description)[];
    12: (string | typeof fromwire_offer_features)[];
    14: (string | typeof fromwire_offer_absolute_expiry)[];
    16: (string | typeof fromwire_offer_paths)[];
    18: (string | typeof fromwire_offer_issuer)[];
    20: (string | typeof fromwire_offer_quantity_max)[];
    22: (string | typeof fromwire_offer_node_id)[];
    80: (string | typeof fromwire_offer_node_id)[];
    82: (string | typeof fromwire_invoice_request_amount)[];
    84: (string | typeof fromwire_invoice_request_features)[];
    86: (string | typeof fromwire_invoice_request_quantity)[];
    88: (string | typeof fromwire_invoice_request_payer_key)[];
    89: (string | typeof fromwire_invoice_request_payer_note)[];
    164: (string | typeof fromwire_invoice_created_at)[];
    166: (string | typeof fromwire_invoice_relative_expiry)[];
    168: (string | typeof fromwire_invoice_payment_hash)[];
    170: (string | typeof fromwire_invoice_amount)[];
    172: (string | typeof fromwire_invoice_fallbacks)[];
    174: (string | typeof fromwire_invoice_features)[];
    176: (string | typeof fromwire_invoice_node_id)[];
    240: (string | typeof fromwire_offer_signature)[];
};
declare function fromwire_offer_chains(buffer: any): any[];
declare function fromwire_offer_currency(buffer: any): any;
declare function fromwire_offer_amount(buffer: any): any;
declare function fromwire_offer_description(buffer: any): any;
declare function fromwire_offer_features(buffer: any): any[];
declare function fromwire_offer_absolute_expiry(buffer: any): number | Buffer;
declare function fromwire_offer_paths(buffer: any): any[];
declare function fromwire_offer_issuer(buffer: any): any;
declare function fromwire_offer_quantity_max(buffer: any): number | Buffer;
declare function fromwire_offer_node_id(buffer: any): any;
declare function fromwire_invoice_request_amount(buffer: any): any;
declare function fromwire_invoice_request_features(buffer: any): any[];
declare function fromwire_invoice_request_quantity(buffer: any): number | Buffer;
declare function fromwire_invoice_request_payer_key(buffer: any): any;
declare function fromwire_invoice_request_payer_note(buffer: any): any;
declare function fromwire_invoice_created_at(buffer: any): number | Buffer;
declare function fromwire_invoice_relative_expiry(buffer: any): number | Buffer;
declare function fromwire_invoice_payment_hash(buffer: any): any;
declare function fromwire_invoice_amount(buffer: any): any;
declare function fromwire_invoice_fallbacks(buffer: any): {
    fallbacks: any[];
};
declare function fromwire_invoice_features(buffer: any): any[];
declare function fromwire_invoice_node_id(buffer: any): any;
declare function fromwire_offer_signature(buffer: any): any;
import { Buffer } from 'buffer';
export {};
